#!/bin/bash

METADATA_FILE=$(dirname $0)/metadata.lsp

PID=$(pgrep shouter)

echo "(artist \"${1}\")" >  ${METADATA_FILE}
echo "(title \"${2}\")"  >> ${METADATA_FILE}
echo "(album \"${3}\")"  >> ${METADATA_FILE}
echo "(length \"${4}\")" >> ${METADATA_FILE}

sleep 15s && kill -s SIGUSR1 ${PID}


